# Generated by Django 5.2.1 on 2025-05-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user_type',
            field=models.CharField(blank=True, choices=[('seller', 'Seller'), ('buyer', 'Buyer'), ('volunteer', 'Volunteer'), ('admin', 'Admin'), ('company', 'Company')], max_length=20, null=True),
        ),
    ]
